export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS';
export const FETCH_BOOKS_LOADING = 'FETCH_BOOKS_LOADING';
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED';

export const ADD_TO_LIBRARY = 'ADD_TO_LIBRARY';
export const REMOVE_FROM_LIBRARY = 'REMOVE_FROM_LIBRARY';